### ISSUE TITLE
Logging in via verification

### ISSUE THREAD

**Issue by dracos** [samyakjain101/django-phone-auth#14]
This looks like a really useful project, thank you. I'm thinking of using it in something where you would have a form that included email and phone, no username/password, and you would then confirm the submission by email or phone (you'd presumably pick which in some manner). Then later on, rather than log in with password, you'd go through another "verification" step to log in instead.

This feels like it should be possible (I could set the username automatically easily enough, then for log-in-by-token creating something similar to `PhoneEmailVerificationForm` for sending a signal and `PhoneEmailVerificationConfirmView` to log in rather than verify), but I thought I'd ask first before diving in in case I have missed something obvious :)

**Comment by samyakjain101** [comment]
Thank you for the kind words.

Do you mean your implementation requires a user to go to the verification step every time a user wants to log in?

If yes, this is possible. Few applications already use it.

But, I have a problem with this approach:

It is slow.
User requests for login link via email/phone -> Server sends an email/SMS -> User opens this link -> Server again validate the token -> Logged In
    
Traditional Approach:
Enter email/phone and password -> Server validates email/phone and password -> Logged In

Still, if it fits your requirements, you can go for it :)

**Comment by dracos** [comment]
Our application is going to be used infrequently by varied people (perhaps with less internet experience); we do not want people to have to set/remember passwords at all. If people are on their phone, then entering a code can be made easier by methods such as `autocomplete="one-time-code"`. Thanks, I'll try and give it a go.
