### ISSUE TITLE
Custom User required?

### ISSUE THREAD

**Issue by Chatelo** [samyakjain101/django-phone-auth#17]
This is not actually an issue but rather a clarification I am seeking. I am building an app based on the library and I am like do I really need to create a custom user or I can use the one shipped with the library. If I have to override the one shipped with the library , , what are other settings/configurations I need to make, same applies if I have to use the one shipped with the lib.

Also help clarify on the registered user, are they active by default?

**Comment by samyakjain101** [comment]
@Chatelo Please check this out:
[Django's Documentation: Using a custom user model when starting a project](https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project)

This library uses user model configured by you whether it's the default or custom.
Yes, user is active by default on registration.

**Comment by Chatelo** [comment]
Thanks alot for the quick response. You're doing great job.

**Comment by samyakjain101** [comment]
No Problem! I'll mark this issue as closed. Feel free to open a new one incase of any questions!
